import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ weight: "500", style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Find Your Tutor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <body className={`${poppins.className} flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
